import { describe, expect, it } from "vitest";
import nodeComposition from "../../apps/main-node/src/index.ts?raw";
import cloudflareComposition from "../../apps/main/src/index.ts?raw";

describe("platform SDK consumer boundary", () => {
  it("composes Node applications through configured platform features", () => {
    expect(nodeComposition).toContain("createNodePlatform");
    expect(nodeComposition).toContain("createNodeManagedAgentsApp");
    expect(nodeComposition).toContain('preset: "none"');
    expect(nodeComposition).toContain("agents: true");
    expect(nodeComposition).toContain("models: true");
    expect(nodeComposition).toContain("managedAgentsPortTokens.agents");
    expect(nodeComposition).toContain("ModelCardCatalogSource");
    expect(nodeComposition).toContain("managedAgentsPortTokens.environments");
    expect(nodeComposition).toContain("environmentWorkEnqueuerModule");
    expect(nodeComposition).toContain("managedAgentsPortTokens.environmentWork");
    expect(nodeComposition).toContain("environmentSessionWorkEnqueuerPort");
    expect(nodeComposition).toContain("dreamExecutionModule");
    expect(nodeComposition).toContain("managedAgentsPortTokens.dreams");
    expect(nodeComposition).toContain("managedAgentsPortTokens.memoryStores");
    expect(nodeComposition).toContain("managedAgentsPortTokens.memories");
    expect(nodeComposition).toContain("managedAgentsPortTokens.memoryVersions");
    expect(nodeComposition).toContain("managedAgentsPortTokens.skills");
    expect(nodeComposition).toContain("managedAgentsPortTokens.skillVersions");
    expect(nodeComposition).toContain("managedAgentsPortTokens.tunnels");
    expect(nodeComposition).toContain("managedAgentsPortTokens.tunnelCertificates");
    expect(nodeComposition).toContain("managedAgentsPortTokens.userProfiles");
    expect(nodeComposition).not.toContain("agentsModule");
    expect(nodeComposition).not.toContain("new ModelsApplicationService({");
    expect(nodeComposition).not.toContain("new AgentsApplicationService({");
    expect(nodeComposition).not.toContain("new EnvironmentsApplicationService({");
    expect(nodeComposition).not.toContain("new EnvironmentWorkApplicationService({");
    expect(nodeComposition).not.toContain("new EnvironmentWorkEnqueuerService({");
    expect(nodeComposition).not.toContain("new SqlEnvironmentWorkPersistence(");
    expect(nodeComposition).not.toContain("new DreamsApplicationService({");
    expect(nodeComposition).not.toContain("new DreamExecutionApplicationService({");
    expect(nodeComposition).not.toContain("new MemoryStoresApplicationService({");
    expect(nodeComposition).not.toContain("new MemoriesApplicationService({");
    expect(nodeComposition).not.toContain("new MemoryVersionsApplicationService({");
    expect(nodeComposition).not.toContain("new SkillsApplicationService({");
    expect(nodeComposition).not.toContain("new SkillVersionsApplicationService({");
    expect(nodeComposition).not.toContain("new TunnelsApplicationService({");
    expect(nodeComposition).not.toContain("new TunnelCertificatesApplicationService({");
    expect(nodeComposition).not.toContain("new UserProfilesApplicationService({");
    expect(nodeComposition).not.toContain("new SqlUserProfilePersistence(");
    expect(nodeComposition).not.toContain("new SqlDreamPersistence(");
  });

  it("composes request-scoped Cloudflare applications through configured features", () => {
    expect(cloudflareComposition).toContain("createCloudflareManagedAgentsApp");
    expect(cloudflareComposition).toContain('preset: "none"');
    expect(cloudflareComposition).toContain("agents: true");
    expect(cloudflareComposition).toContain("models: true");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.agents");
    expect(cloudflareComposition).toContain("ModelCardCatalogSource");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.environments");
    expect(cloudflareComposition).toContain("environmentWorkEnqueuerModule");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.environmentWork");
    expect(cloudflareComposition).toContain("environmentSessionWorkEnqueuerPort");
    expect(cloudflareComposition).toContain("dreamExecutionModule");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.dreams");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.memoryStores");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.memories");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.memoryVersions");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.skills");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.skillVersions");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.tunnels");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.tunnelCertificates");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.userProfiles");
    expect(cloudflareComposition).not.toContain("createCloudflarePlatform");
    expect(cloudflareComposition).not.toContain("agentsModule");
    expect(cloudflareComposition).not.toContain("new ModelsApplicationService({");
    expect(cloudflareComposition).not.toContain("new AgentsApplicationService({");
    expect(cloudflareComposition).not.toContain("new EnvironmentsApplicationService({");
    expect(cloudflareComposition).not.toContain("new EnvironmentWorkApplicationService({");
    expect(cloudflareComposition).not.toContain("new EnvironmentWorkEnqueuerService({");
    expect(cloudflareComposition).not.toContain("new SqlEnvironmentWorkPersistence(");
    expect(cloudflareComposition).not.toContain("new DreamsApplicationService({");
    expect(cloudflareComposition).not.toContain("new DreamExecutionApplicationService({");
    expect(cloudflareComposition).not.toContain("new MemoryStoresApplicationService({");
    expect(cloudflareComposition).not.toContain("new MemoriesApplicationService({");
    expect(cloudflareComposition).not.toContain("new MemoryVersionsApplicationService({");
    expect(cloudflareComposition).not.toContain("new SkillsApplicationService({");
    expect(cloudflareComposition).not.toContain("new SkillVersionsApplicationService({");
    expect(cloudflareComposition).not.toContain("new TunnelsApplicationService({");
    expect(cloudflareComposition).not.toContain("new TunnelCertificatesApplicationService({");
    expect(cloudflareComposition).not.toContain("new UserProfilesApplicationService({");
    expect(cloudflareComposition).not.toContain("new SqlUserProfilePersistence(");
    expect(cloudflareComposition).not.toContain("new SqlDreamPersistence(");
  });
});
