import { describe, expect, it } from "vitest";
import nodeComposition from "../../apps/main-node/src/index.ts?raw";
import cloudflareComposition from "../../apps/main/src/index.ts?raw";

describe("platform SDK consumer boundary", () => {
  it("resolves the Node Agents application through the workspace app graph", () => {
    expect(nodeComposition).toContain("createNodePlatform");
    expect(nodeComposition).toContain("agentsModule");
    expect(nodeComposition).toContain("managedAgentsPortTokens.agents");
    expect(nodeComposition).toContain("new ModelsApplicationService({");
    expect(nodeComposition).toContain("ModelCardCatalogSource");
    expect(nodeComposition).toContain("environmentsModule");
    expect(nodeComposition).toContain("managedAgentsPortTokens.environments");
    expect(nodeComposition).toContain("environmentWorkModule");
    expect(nodeComposition).toContain("environmentWorkEnqueuerModule");
    expect(nodeComposition).toContain("managedAgentsPortTokens.environmentWork");
    expect(nodeComposition).toContain("environmentSessionWorkEnqueuerPort");
    expect(nodeComposition).toContain("dreamsModule");
    expect(nodeComposition).toContain("dreamExecutionModule");
    expect(nodeComposition).toContain("managedAgentsPortTokens.dreams");
    expect(nodeComposition).toContain("memoryStoresModule");
    expect(nodeComposition).toContain("managedAgentsPortTokens.memoryStores");
    expect(nodeComposition).toContain("memoriesModule");
    expect(nodeComposition).toContain("memoryVersionsModule");
    expect(nodeComposition).toContain("managedAgentsPortTokens.memories");
    expect(nodeComposition).toContain("managedAgentsPortTokens.memoryVersions");
    expect(nodeComposition).toContain("skillsModule");
    expect(nodeComposition).toContain("skillVersionsModule");
    expect(nodeComposition).toContain("managedAgentsPortTokens.skills");
    expect(nodeComposition).toContain("managedAgentsPortTokens.skillVersions");
    expect(nodeComposition).toContain("tunnelsModule");
    expect(nodeComposition).toContain("tunnelCertificatesModule");
    expect(nodeComposition).toContain("managedAgentsPortTokens.tunnels");
    expect(nodeComposition).toContain("managedAgentsPortTokens.tunnelCertificates");
    expect(nodeComposition).toContain("userProfilesModule");
    expect(nodeComposition).toContain("managedAgentsPortTokens.userProfiles");
    expect(nodeComposition).not.toContain("new AgentsApplicationService({");
    expect(nodeComposition).not.toContain("new EnvironmentsApplicationService({");
    expect(nodeComposition).not.toContain("new EnvironmentWorkApplicationService({");
    expect(nodeComposition).not.toContain("new EnvironmentWorkEnqueuerService({");
    expect(nodeComposition).not.toContain("new SqlEnvironmentWorkPersistence(");
    expect(nodeComposition).not.toContain("new DreamsApplicationService({");
    expect(nodeComposition).not.toContain("new DreamExecutionApplicationService({");
    expect(nodeComposition).not.toContain("new MemoryStoresApplicationService({");
    expect(nodeComposition).not.toContain("new MemoriesApplicationService({");
    expect(nodeComposition).not.toContain("new MemoryVersionsApplicationService({");
    expect(nodeComposition).not.toContain("new SkillsApplicationService({");
    expect(nodeComposition).not.toContain("new SkillVersionsApplicationService({");
    expect(nodeComposition).not.toContain("new TunnelsApplicationService({");
    expect(nodeComposition).not.toContain("new TunnelCertificatesApplicationService({");
    expect(nodeComposition).not.toContain("new UserProfilesApplicationService({");
    expect(nodeComposition).not.toContain("new SqlUserProfilePersistence(");
    expect(nodeComposition).not.toContain("new SqlDreamPersistence(");
  });

  it("resolves the Cloudflare Agents application through the workspace app graph", () => {
    expect(cloudflareComposition).toContain("createCloudflarePlatform");
    expect(cloudflareComposition).toContain("agentsModule");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.agents");
    expect(cloudflareComposition).toContain("new ModelsApplicationService({");
    expect(cloudflareComposition).toContain("ModelCardCatalogSource");
    expect(cloudflareComposition).toContain("environmentsModule");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.environments");
    expect(cloudflareComposition).toContain("environmentWorkModule");
    expect(cloudflareComposition).toContain("environmentWorkEnqueuerModule");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.environmentWork");
    expect(cloudflareComposition).toContain("environmentSessionWorkEnqueuerPort");
    expect(cloudflareComposition).toContain("dreamsModule");
    expect(cloudflareComposition).toContain("dreamExecutionModule");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.dreams");
    expect(cloudflareComposition).toContain("memoryStoresModule");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.memoryStores");
    expect(cloudflareComposition).toContain("memoriesModule");
    expect(cloudflareComposition).toContain("memoryVersionsModule");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.memories");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.memoryVersions");
    expect(cloudflareComposition).toContain("skillsModule");
    expect(cloudflareComposition).toContain("skillVersionsModule");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.skills");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.skillVersions");
    expect(cloudflareComposition).toContain("tunnelsModule");
    expect(cloudflareComposition).toContain("tunnelCertificatesModule");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.tunnels");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.tunnelCertificates");
    expect(cloudflareComposition).toContain("userProfilesModule");
    expect(cloudflareComposition).toContain("managedAgentsPortTokens.userProfiles");
    expect(cloudflareComposition).not.toContain("new AgentsApplicationService({");
    expect(cloudflareComposition).not.toContain("new EnvironmentsApplicationService({");
    expect(cloudflareComposition).not.toContain("new EnvironmentWorkApplicationService({");
    expect(cloudflareComposition).not.toContain("new EnvironmentWorkEnqueuerService({");
    expect(cloudflareComposition).not.toContain("new SqlEnvironmentWorkPersistence(");
    expect(cloudflareComposition).not.toContain("new DreamsApplicationService({");
    expect(cloudflareComposition).not.toContain("new DreamExecutionApplicationService({");
    expect(cloudflareComposition).not.toContain("new MemoryStoresApplicationService({");
    expect(cloudflareComposition).not.toContain("new MemoriesApplicationService({");
    expect(cloudflareComposition).not.toContain("new MemoryVersionsApplicationService({");
    expect(cloudflareComposition).not.toContain("new SkillsApplicationService({");
    expect(cloudflareComposition).not.toContain("new SkillVersionsApplicationService({");
    expect(cloudflareComposition).not.toContain("new TunnelsApplicationService({");
    expect(cloudflareComposition).not.toContain("new TunnelCertificatesApplicationService({");
    expect(cloudflareComposition).not.toContain("new UserProfilesApplicationService({");
    expect(cloudflareComposition).not.toContain("new SqlUserProfilePersistence(");
    expect(cloudflareComposition).not.toContain("new SqlDreamPersistence(");
  });
});
